export enum ActivityTypeConstant {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  PAYMENT = 'PAYMENT',
  AUTHENTICATION = 'AUTHENTICATION',
  SERVICE_FEE_AND_BILL_GENERATION = 'SERVICE_FEE_AND_BILL_GENERATION'
}
