export enum WalletWithdrawalEnum {
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  PENDING = 'PENDING',
  WAITING_CONFIRMATION = 'WAITING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED'
}
