import { ModelFactory } from '../common/test-starter/orm-faker/contracts/ModelFactory';
import { Setting } from '../domain/entity/setting.entity';
import { SettingModelFactory } from './factory/setting-model.factory';
import { PortalUser } from '../domain/entity/portal-user.entity';
import { PortalUserModelFactory } from './factory/portal-user-model.factory';
import { PortalAccount } from '../domain/entity/portal-account.entity';
import { PortalAccountModelFactory } from './factory/portal-account-model.factory';
import { Membership } from '../domain/entity/membership.entity';
import { MembershipModelFactory } from './factory/membership-model.factory';
import { FileModelFactory } from './factory/file-model.factory';
import { FileResource } from '../domain/entity/file.entity';
import { Address } from '../domain/entity/address.entity';
import { AddressModelFactory } from './factory/address-model.factory';
import { Country } from '../domain/entity/country.entity';
import { CountryModelFactory } from './factory/country-model.factory';
import { Association } from '../domain/entity/association.entity';
import { AssociationModelFactory } from './factory/association-model.factory';
import { Bank } from '../domain/entity/bank.entity';
import { BankFactory } from './factory/bank.factory';
import { ServiceFee } from '../domain/entity/service.fee.entity';
import { ServiceFeeFactory } from './factory/service-fee.factory';
import { Group } from '../domain/entity/group.entity';
import { GroupModelFactory } from './factory/group-model.factory';
import { GroupMembership } from '../domain/entity/group-membership.entity';
import { GroupMembershipModelFactory } from './factory/group-membership-model.factory';
import { GroupServiceFee } from '../domain/entity/group-sevice-fee.entity';
import { GroupServiceFeeModelFactory } from './factory/group-service-fee-model.factory';
import { Subscription } from '../domain/entity/subcription.entity';
import { SubscriptionModelFactory } from './factory/subscription-model.factory';
import { Bill } from '../domain/entity/bill.entity';
import { BillModelFactory } from './factory/bill-model.factory';
import { Invoice } from '../domain/entity/invoice.entity';
import { InvoiceModelFactory } from './factory/invoice-model.factory';
import { PaymentRequestFactory } from './factory/payment-request.factory';
import { PaymentRequest } from '../domain/entity/payment-request.entity';
import { Wallet } from '../domain/entity/wallet.entity';
import { WalletFactory } from './factory/wallet.factory';
import { BankInfo } from '../domain/entity/bank-info.entity';
import { BankInfoFactory } from './factory/bank-info.factory';
import { PaymentTransaction } from '../domain/entity/payment-transaction.entity';
import { PaymentTransactionModelFactory } from './factory/payment-transaction-model.factory';
import { ActivityLogModelFactory } from './factory/activity-log-model.factory';
import { ActivityLog } from '../domain/entity/activity-log.entity';
import { MembershipInfo } from '../domain/entity/association-member-info.entity';
import { MembershipInfoFactory } from './factory/membership-info.factory';
import { BillInvoice } from '../domain/entity/bill-invoice.entity';
import { BillInvoiceFactory } from './factory/bill-invoice.factory';
import { Role } from '../domain/entity/role.entity';
import { RoleFactory } from './factory/role.factory';
import { Permission } from '../domain/entity/permission.entity';
import { PermissionFactory } from './factory/permission.factory';
import { RolePermission } from '../domain/entity/role-permission.entity';
import { RolePermissionFactory } from './factory/role-permission.factory';
import { MembershipRoleFactory } from './factory/membership-role.factory';
import { MembershipRole } from '../domain/entity/membership-role.entity';
import { WalletTransaction } from '../domain/entity/wallet-transaction.entity';
import { WalletTransactionFactory } from './factory/wallet-transaction.factory';
import { WalletWithdrawal } from '../domain/entity/wallet-withdrawal.entity';
import { WalletWithdrawalFactory } from './factory/wallet-withdrawal.factory';
import { AccountDetail } from '../domain/entity/account-detail.entity';
import { AccountDetailModelFactory } from './factory/account-detail-model.factory';

export class ModelFactoryRoster {
  static register(modelFactory: ModelFactory) {
    modelFactory.register<Setting, SettingModelFactory>(Setting, SettingModelFactory);
    modelFactory.register<PortalUser, PortalUserModelFactory>(PortalUser, PortalUserModelFactory);
    modelFactory.register(PortalAccount, PortalAccountModelFactory);
    modelFactory.register(Membership, MembershipModelFactory);
    modelFactory.register(FileResource, FileModelFactory);
    modelFactory.register(Address, AddressModelFactory);
    modelFactory.register(Country, CountryModelFactory);
    modelFactory.register(Association, AssociationModelFactory);
    modelFactory.register(Bank, BankFactory);
    modelFactory.register(Group, GroupModelFactory);
    modelFactory.register(ServiceFee, ServiceFeeFactory);
    modelFactory.register(GroupMembership, GroupMembershipModelFactory);
    modelFactory.register(GroupServiceFee, GroupServiceFeeModelFactory);
    modelFactory.register(Subscription, SubscriptionModelFactory);
    modelFactory.register(Bill, BillModelFactory);
    modelFactory.register(Invoice, InvoiceModelFactory);
    modelFactory.register(PaymentRequest, PaymentRequestFactory);
    modelFactory.register(Wallet, WalletFactory);
    modelFactory.register(BankInfo, BankInfoFactory);
    modelFactory.register(PaymentTransaction, PaymentTransactionModelFactory);
    modelFactory.register(ActivityLog, ActivityLogModelFactory);
    modelFactory.register(MembershipInfo, MembershipInfoFactory);
    modelFactory.register(BillInvoice, BillInvoiceFactory);
    modelFactory.register(Role, RoleFactory);
    modelFactory.register(Permission, PermissionFactory);
    modelFactory.register(RolePermission, RolePermissionFactory);
    modelFactory.register(MembershipRole, MembershipRoleFactory);
    modelFactory.register(WalletTransaction, WalletTransactionFactory);
    modelFactory.register(WalletWithdrawal, WalletWithdrawalFactory);
    modelFactory.register(AccountDetail, AccountDetailModelFactory);
  }
}
