export enum CronQueue {
  SUBSCRIPTION = 'SUBSCRIPTION',
  BILL_GENERATION = 'BILL_GENERATION'
}

export enum QueueNames {
  REOCCURRING_SUBSCRIPTION_GENERATION = 'REOCCURRING_SUBSCRIPTION_GENERATION',
  ONETIME_SUBSCRIPTION_GENERATION = 'ONETIME_SUBSCRIPTION_GENERATION',
}