export enum Queues {
  SUBSCRIPTION = 'SUBSCRIPTION',
  BILL_GENERATION = 'BILL_GENERATION',
  EMAIL = 'EMAIL',
  WALLET_WITHDRAWAL = 'WALLET_WITHDRAWAL'
}

export enum QueueNames {
  REOCCURRING_SUBSCRIPTION_GENERATION = 'REOCCURRING_SUBSCRIPTION_GENERATION',
  ONETIME_SUBSCRIPTION_GENERATION = 'ONETIME_SUBSCRIPTION_GENERATION',
}
