export enum AccessTypes {
  PUBLIC = 'PUBLIC',
  TRUSTED_IP = 'TRUSTED_IP',
  LOCALHOST = 'LOCALHOST',
  LOG = 'LOG',
  ASSOCIATION = 'ASSOCIATION',
  HAS_MEMBERSHIP = 'HAS_MEMBERSHIP',
  HAS_PERMISSION = 'HAS_PERMISSION'
}
