export const FLUTTERWAVETRANSACTION = 'FLUTTERWAVE_TRANSACTION';
export const PAYMENT_CONFIG = 'PAYMENT_CONFIG';
export const HTTP_CLIENT_PROVIDER = 'HTTP_CLIENT_PROVIDER';
export const FLUTTERWAVEBANKVERIFICATION = 'FLUTTERWAVE_BANK_VERIFICATION';
export const FLUTTERWAVEWITHDRAWAL = 'FLUTTER_WAVE_WITHDRAWAL';
